name: Create Cluster

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0

      - name: Testing
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
          cat ${KUBECONFIG}

      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Print Public IP
        run: |
          echo ${{ steps.ip.outputs.ipv4 }}
          echo ${{ steps.ip.outputs.ipv6 }}

      - name: Install
        run: |
          helm repo add nginx-stable https://helm.nginx.com/stable
          helm repo update
          helm install my-release nginx-stable/nginx-ingress --set controller.service.externalIPs="[${{ steps.ip.outputs.ipv4 }}]"

      - name: Curl
        run: |
          curl http://${{ steps.ip.outputs.ipv4 }}.nip.io
